### ISSUE TITLE
你这个配置和clash meta核有冲突 无论是openclash的meta还是手搓的linux clash meta填上你这配置的就翻墙无望

### ISSUE THREAD

**Issue by issachigga** [Journalist-HK/mosdns-config#2]

**Comment by Journalist-HK** [comment]
我确实不使用 meta 内核，你得提供一下 log 才能分析问题。不过你可以先把 mosdns 部署在别的机器上试试。

**Comment by Journalist-HK** [comment]
如果你是用了 TUN 然后 hijack dns 使 mosdns 没法请求 UDP 上游，那你只用 DoH 上游就行了。

**Comment by issachigga** [comment]
我不太懂啊 就是用meta 进去clash界面ping节点都ping不通 看了下log全部超时 这个是吧forward里面的remote的UDP改成DoH吗 还是咋地

> 如果你是用了 TUN 然后 hijack dns 使 mosdns 没法请求 UDP 上游，那你只用 DoH 上游就行了。

**Comment by Journalist-HK** [comment]
把 config_custom.yaml 里的 `$forward_local` 换成 `$forward_alidns` 试试。你用 nslookup 或者 dig 能返回正常结果吗？

**Comment by issachigga** [comment]
> 把 config_custom.yaml 里的 `$forward_local` 换成 `$forward_alidns` 试试。你用 nslookup 或者 dig 能返回正常结果吗？

大佬在线啊 我现在去试试 还有我是用的mos就是在别的机器部署 openwrt本机原装配置的是可以用meta

**Comment by issachigga** [comment]
行了大佬 感谢
