### ISSUE TITLE
BT pt下载链接能否分流出来呢？

### ISSUE THREAD

**Issue by llity** [Journalist-HK/mosdns-config#8]
bt下载的一些种子链接似乎没有过滤出来，被转发给sing-box了
![image](https://github.com/user-attachments/assets/a73dc512-1d0c-48f5-b474-aa6d35a65d97)

**Comment by Journalist-HK** [comment]
bt 和这个 dns 有什么关系，这图里的 tracker 不是可以正常解析吗？

**Comment by llity** [comment]
> bt 和这个 dns 有什么关系，这图里的 tracker 不是可以正常解析吗？

我想能否在mosdns里面把tracker的解析转发到国内，现在是被识别为remote转发到代理软件了

**Comment by llity** [comment]
还发现一个最新配置文件mosdns无法启动了，irinesistiana/mosdns:v5.3.1 日志如下
Error: failed to load config from ./load_rules.yaml, failed to init plugin #0 redirect, failed to init plugin: failed to load file #0 ./rule/redirect.txt, line 1: redirect rule must have 2 fields, but got 3

https://ghproxy.cc/https://raw.githubusercontent.com/Journalist-HK/Rules/main/rediect.txt 这个文件是空的
![image](https://github.com/user-attachments/assets/6db6d01e-6bd0-48f6-be80-08fb1b626872)

**Comment by Journalist-HK** [comment]
> 我想能否在mosdns里面把tracker的解析转发到国内，现在是被识别为remote转发到代理软件了

把域名添加到对应的名单里就可以了，这些规则这是示例，有需求自行修改即可。
